### PR TITLE
Add JSCS

### PR DESCRIPTION
**Pull request by adrianheine**

### CODE REVIEW

**Comment by adrianheine** [comment]
@thiemowmde @snaterlicious

**Comment by thiemowmde** [comment]
Checked with `diff -w`, almost all changes are white-space changes, and a few commas are removed.

**Comment by thiemowmde** [comment]
+2 from my side, but I would like to understand what the deal with the deleted shell script is?

**Comment by adrianheine** [comment]
Dunno, I just followed wikimedia/nagf#1. @JeroenDeDauw?

**Comment by adrianheine** [comment]
ping @JeroenDeDauw @thiemowmde @snaterlicious

**Comment by JeroenDeDauw** [comment]
Cool

**Pull request merged**
